tapglue/snaas

cmd/gateway-http/gateway-http.go, cmd/sims/channel.go, cmd/sims/consume.go, cmd/sims/endpoint.go, cmd/sims/platform.go, cmd/sims/rules.go, cmd/sims/sims.go, core/app.go, core/comment.go, core/connection.go, core/device.go, core/like.go, core/post.go, core/user.go, platform/sns/error.go, platform/sns/sns.go, platform/source/source.go, service/app/app.go, service/app/helper_test.go, service/app/postgres.go, service/connection/connection.go, service/event/event.go, service/object/object.go
Wherein we implement a new worker binary called SIMS (Signal informed Messaging Service) which consumes the state changes emitted by the API and by applying rules determines who to send transactional messages to. In this first iteration we only target mobile platforms with push messages. As the delivery platform SNS is supported and used for the bookkeeping of endpoint per device.
* implment SIMS binary
* add rules for:
- new follower
- new friend request
- friend request confirmed
- new like
- new comment
- new post
* introduce SNS as push delivery platform
=> Introduce SIMS worker

TODO, cmd/terraformer/terraformer.go, infrastructure/terraform/template/network.tf, infrastructure/terraform/template/platform.tf, infrastructure/terraform/template/scheduling.tf, infrastructure/terraform/template/security.tf, infrastructure/terraform/template/storage.tf, infrastructure/terraform/template/variables.tf
Wherein we try to simplify the infrastructure to the point where we don't need custom AMIs and extensive tooling to create Docker containers. We achieve the first one by using of-the-shelf AMIs offered in marketplaces and/or advertised by AWS. The second one is solved with using a public repository[0] on DockerHub.
* use pre-maded images
* use configured SSH key
* introduce simple TODO list
=> Simplify infrastructure

TODO, circle.yml, infrastructure/docker/snaas.docker, infrastructure/scripts/build-container
In order to distribute our core software we introduce centralised, public images on DockerHub which are fed by artifacts created in the CI build pipeline.
=> Enable Docker build pipeline

TODO, cmd/terraformer/terraformer.go
In order to empower the user to access the infrastructure after the setup we require the input of an SSH public key which is used to bootstrap key nodes like the Bastion and monitoring host.
=> Require SSH key during setup

core/device.go, service/device/postgres.go
Up until now we used device_id and user_id to check for uniqueness, which is not reliable when installation of an app from mixed sources takes place as the device_id might change and the token stays the same. This will result in multiple registered devices and lead to notification duplicates.
=> Fix uniqueness constrain on devices

core/feed.go
So far we didn't provide the relation status for users passed along in feed responses, which creates sub-optimal user experience when that information is used for connection related interactions.
=> Enrich relation information in feed responses

cmd/dataz/dataz.go
Wherein we introduce dataz a binary to export and import data, which in the first iteration uses newline delimited json files per entity. It supports export and import as commands which aim to work symmetrically. We choose the application as capsule for export and import to avoid more involved migration coordination/logic. The user must be aware of the namespace of the application that they want to export, where on import a new application is created and the namespace is logged.
Example usage:
```
./dataz \
-data.dir "app_1_2" \
-namespace "app_1_2" \
-postgres.url "$PG_URL"
export
```
=> Implemenet data migration tool

core/feed.go
All other feeds include them, this is correcting an oversight when implementing the notifications feed.
=> Add counts for posts in notifications feed

cmd/gateway-http/gateway-http.go, core/post.go, core/post_test.go
To be consistent with other lists and the company entities meta information we add relation status to users returned in post lists.
=> Add relation information in post lists

handler/http/user.go
This was missing and wasn't symmetrical over all search endpoints.
=> Add pagination to user search endpoints

core/connection.go, handler/http/connection.go
One of the last endpoints that was missing pagination, which is inconsistent with the rest of the list endpoints. As connections are ordered by their update time we can chunk the pages by that dimension even when the representation returned is split by direction of the connection.
=> Add pagination to connection listed by state

cmd/terraformer/terraformer.go, infrastructure/terraform/template/network.tf, infrastructure/terraform/template/platform.tf, infrastructure/terraform/template/routing.tf, infrastructure/terraform/template/scheduling.tf, infrastructure/terraform/template/storage.tf, infrastructure/terraform/template/variables.tf
In order to make an env publicily reachable we introduce the handling of an additional zone which is part of the user input during setup. Additionally we make the use of an acm certificate to provide proper termination for the traffic layer.
=> Add Public routing

core/comment.go, core/connection.go, core/like.go
This adds the relation info to the user representations in lists where it was missing until now.
=> Enrich all users with relation info

core/feed.go, core/feed_test.go
As it would put additional burden on the client to distinct which user to get (target or normal) we just always use the connected user to avoid potentially breaking and spotty logic.
=> Always reference the connected uesr in connection events

core/feed.go
To guarantee a better experience the posts of a user should be presented along side the posts of the network and promoted content.
=> Include own posts in post feed

TODO, cmd/sims/channel.go, cmd/sims/platform.go, cmd/sims/sims.go, core/device.go, core/platform.go, error/error.go, handler/http/device.go, handler/http/platform.go, infrastructure/terraform/template/storage.tf, platform/sns/sns.go, service/device/device.go, service/device/helper_test.go, service/platform/helper_test.go, service/platform/platform.go, service/platform/platform_test.go, service/platform/postgres.go, service/platform/postgres_test.go
Which are used as the book-keeping glue between Apps and the SNS entity used for notification routing.
* implement platform service
* implement platform create handler (not mounted)
* implement platform create and fetch by ARN or active per app
* add first centralised errors
=> Implement Application Platforms

service/object/object.go, service/object/object_test.go
With the increased use of tags esp. for semantic distinction of posts the current limit turns out to be not sufficient when semantic tags are mixed with user input. There might be an opportunity to split those apart to avoid unnecessary side-effects.
=> Raise tag limit for objects

doc/notifications-structure-android.md, platform/sns/sns.go
The current structure of the notification payload on android does not allow for customisation on the client side. When a `notification` object is present the only customisation possible is the notification icon and the primary color.
Replace the notification message with a data message. Documentation on both types can be found [here](https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages)
1. Add the data from the `notification` object to the `data` object.
2. Put the `data` object on the top level
2. Remove the `notification` object.
The names of the fields in the `notification` object could be the same in the `data` object. This way the client has to manually handle their notifications, which gives it the liberty to customise the design.
This …
=> Android notification structure

core/device.go, service/device/device.go, service/device/helper_test.go, service/device/postgres.go
In case the same device is registered with a new user it can lead to receiving push notifications not targeted at the user. To alleviate this we check if their is a device with the same token regardless which user it belongs to.
=> Fix double device registration

cmd/terraformer/terraformer.go, infrastructure/terraform/template/files/dashboard-ops.json, infrastructure/terraform/template/platform.tf, infrastructure/terraform/template/scripts/setup_monitoring.sh, infrastructure/terraform/template/security.tf, infrastructure/terraform/template/variables.tf
This sets up Prometheus which scrapes the service binaries and host data which then is presented in an operation dashboard in Grafana. For easy access we provide another public endpoint via:
`monitoring-$env-$region-$domain`
While we want simple availability it should not be exposed to the greater public, therefore the Grafana installation is guarded with a Google login. This forces us to require a Google OAuth client id and secret during setup.
* setup prometheus
* setup grafana
* setup operations dashboard
=> Add Prometheus based monitoring

core/feed.go, core/like.go, core/post.go, handler/http/post.go
For client to reason if the user has reacted to a post with one of the available reactions we extend the Post representation with the `has_reacted` field which has a boolean for every of the possible
reactions.
```
{
...
"has_reacted": {
"live": false,
"love": false,
"haha": true,
...
},
...
}
```
=> Add reaction state to posts

cmd/gateway-http/gateway-http.go, cmd/sims/consume.go, cmd/sims/sims.go, core/pipieline.go, core/pipieline_test.go, error/error.go, infrastructure/terraform/template/storage.tf, service/event/event.go, service/event/logging.go, service/reaction/helper_test.go, service/reaction/instrumentation.go, service/reaction/logging.go, service/reaction/mem.go, service/reaction/postgres.go, service/reaction/reaction.go, service/reaction/sourcing.go, service/reaction/sqs.go, service/rule/rule.go
We want to enable the creation of notifications for reaction changes symmetrically to connections, events and objects. Therefore we introduce a new SQS-based source for them.
=> Reaction source

cmd/gateway-http/gateway-http.go, core/invite.go, core/user.go, handler/http/invite.go, handler/http/query.go, handler/http/user.go, platform/flake/flake.go, service/invite/helper_test.go, service/invite/instrumentation.go, service/invite/invite.go, service/invite/logging.go, service/invite/postgres.go, service/invite/postgres_test.go, service/reaction/postgres.go
To enable a better on-boarding experience we need a way to correlate users and their inviter. One way is to keep a list of invites of a user that stores a unique id (e.g. facebook id, or generate random identifier) which can be kept through until the invitee hits the signup. If the invitee signs up and the conenction to the inviter is preserved we can automatically create connections for those so they can hit the ground running.
To create an invite from the current user the following endpoint should be called. The key and value are entirely up to the caller to decide, but must match one of the key/value pairs in the [`social_ids`](https://github.com/tapglue/snaas/wiki/the-user-object#social-ids) of the invitee during signup. Given the Facebook id of the invitee is known:
```
> POST …
```
=> Invite flow

cmd/sims/channel.go, core/pipieline.go, core/pipieline_test.go
To finally support all the local notifications we need a way to send the configured template per language in the actual notification. This change compiles all templates for all messages before returning it as part of a map from the pipeline. This could certainly be improved to not do unnecessary work but would need that the channel which has the device knowledge has to know about the templates, either way could be wasteful. For now we trade cpu time for complexity.
=> Carry precompiled templates from notification pipeline

.gitignore, cmd/console/console.go, cmd/console/src/Action.elm, cmd/console/src/Error.elm, cmd/console/src/Model.elm, cmd/console/src/Route.elm, cmd/console/src/Update.elm, cmd/console/src/User/Api.elm, cmd/console/src/User/Model.elm, cmd/console/src/User/View.elm, cmd/console/src/View.elm, cmd/console/styles/console.css, core/user.go, handler/http/user.go
To allow interaction on user entities this uses the search functionality to fetch a user and update basic data of the user. This is the beginning and can be extended with many features like (de)activate, show owned entities of the user and their connections with others.
=> Add user search and update to Console

cmd/gateway-http/gateway-http.go, core/counter.go, handler/http/counter.go, handler/http/query.go, service/counter/counter.go, service/counter/postgres.go, service/counter/postgres_test.go
This adds a simple way to have namespaced counters per user and get the global count per namespace. In essence this can be used for a variety of use-cases, e.g. leaderboards, group challenges, etc. Introducing only the barest of functionality it will be extended as use-cases arise and applications have been identified. A variety of dimensions might be added for future extension to have contextual leadboards, for example slicing by location, user core data or free form tags.
Counter payload:
```
{
"value": 123
}
```
In the first iteration we support two endpoints:
* `PUT /me/counters/<counterName>`: Expects the counter payload and sets the named counter for the current user to the given value.
* `GET /counters/<counterName>`: Returns the sum of all values for all users for the named …
=> Add Counters

core/feed.go, core/post.go, core/reaction.go, handler/http/post.go, service/reaction/cache.go, service/reaction/helper_test.go, service/reaction/instrumentation.go, service/reaction/logging.go, service/reaction/mem.go, service/reaction/mem_test.go, service/reaction/postgres.go, service/reaction/postgres_test.go, service/reaction/reaction.go, service/reaction/sourcing.go
Since the introduction of reactions one of the biggest impacts on response times for feed/list requests has been the constant overhead of countless network requests in order to populate counters for posts. This is due the nature how we constructed the service interfaces. In this change-set we introduce a specialised method to get all counts for a list of posts at once. After we verify that this does impact the response times significantly we can mirror the same idea in the cache layer.
=> Implement reaction multi count
